# Generated by Django 5.1.7 on 2025-04-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_community_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='interest_tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='community',
            name='meeting_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
