# Generated by Django 5.1.7 on 2025-04-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='post_attachments/'),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('members', 'Community Members Only')], default='public', max_length=10),
        ),
    ]
